{% set version = "3.0.0" %}

package:
  name: auditwheel
  version: {{ version }}

source:
  fn: auditwheel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/auditwheel/auditwheel-{{ version }}.tar.gz
  md5: d2bfce7e0e6ee0d3a6fc4d096326a48e

build:
  number: 0
  skip: True  # [py2k or not linux]

requirements:
  build:
    - pbr
    - python
    - setuptools
    - pyelftools
    - typing      # [py<35]

  run:
    - python
    - setuptools
    - pip
    - pyelftools
    - typing      # [py<35]

test:
  commands:
    - auditwheel -h

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  license_file: LICENSE
  summary: Linux wheel verification tool to ensure compatibility

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
