{% set name = "auditwheel" %}
{% set version = "6.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/auditwheel/auditwheel-{{ version }}.tar.gz
  sha256: 11e611f7090b6cf4075535b88f4364819b849d82702dabb0947cf7c9c5d587a0

build:
  entry_points:
    - auditwheel = auditwheel.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    # Previously the package used to have a requirement on __linux since the it heavily rely on
    # readelf etc. tools (the CLI in particular).
    # However some part of the library are still universally useful so it was removed by user
    # requests.
    # This is akin the the PyPI package which can be installed on any platform.
    - packaging >=20.9
    - python >={{ python_min }}
    - pyelftools >=0.24

test:
  imports:
    - auditwheel
  commands:
    - pip check
    - auditwheel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  license_file:
    - LICENSE
    - src/auditwheel/_vendor/wheel/LICENSE.txt
  summary: Linux wheel verification tool to ensure compatibility

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - BastianZim
