{% set version = "1.4.0" %}

package:
  name: auditwheel
  version: {{ version }}

source:
  fn: auditwheel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/auditwheel/auditwheel-{{ version }}.tar.gz
  sha256: 8cf3e4302361447e76a6b4ff452bce01f9905e349365850774c3e16a8448b0ce

build:
  number: 0
  skip: True  # [py2k or not linux]

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - setuptools
    - pip
    - pyelftools
    - typing      # [py<35]

test:
  commands:
    - auditwheel -h

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  summary: Linux wheel verification tool to ensure compatibility

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
