{% set name = "auditwheel" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/auditwheel/auditwheel-{{ version }}.tar.gz
  sha256: 4fc9f778cd81dac56820e8cdee9842dc44b8f435f8783606dabd4964d4638b30

build:
  entry_points:
    - auditwheel = auditwheel.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - packaging >=20.9
    - python >=3.8
    - pyelftools >=0.24
    - __linux

test:
  imports:
    - auditwheel
  commands:
    - pip check
    - auditwheel --help
  requires:
    - pip

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  license_file:
    - LICENSE
    - src/auditwheel/_vendor/wheel/LICENSE.txt
  summary: Linux wheel verification tool to ensure compatibility

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - BastianZim
